import Btc from "@/assets/images/btc.png";
import Eth from "@/assets/images/eth.svg";
import Ltc from "@/assets/images/ltc.svg";
import Usdt from "@/assets/images/usdt.svg";
import Trx from "@/assets/images/trx.svg";
import Usdc from "@/assets/images/usdc.svg";
import Bnb from "@/assets/images/bnb.svg";
import Bch from "@/assets/images/bch.svg";
import Doge from "@/assets/images/doge.svg";
import Xmr from "@/assets/images/xmr.svg";
import Xlm from "@/assets/images/xlm.svg";
import Xtz from "@/assets/images/xtz.svg";
import Eos from "@/assets/images/eos.svg";
import Shib from "@/assets/images/shib.svg";
import LinkCoin from "@/assets/images/link.svg";
import Etc from "@/assets/images/etc.svg";
import Xrp from "@/assets/images/xrp.svg";
import Ada from "@/assets/images/ada.svg";
import Dash from "@/assets/images/dash.svg";
import Zec from "@/assets/images/zec.svg";
import Sol from "@/assets/images/sol.svg";
import Luna from "@/assets/images/luna.svg";
import Ape from "@/assets/images/ape.svg";
import Dot from "@/assets/images/dot.svg";
import Matic from "@/assets/images/matic.svg";
import Near from "@/assets/images/near.svg";
import Twt from "@/assets/images/twt.svg";
import Rvn from "@/assets/images/rvn.svg";
import Woo from "@/assets/images/woo.svg";
import Gal from "@/assets/images/gal.svg";
import Gno from "@/assets/images/gno.svg";
import Astr from "@/assets/images/astr.svg";
import Nexo from "@/assets/images/nexo.svg";
import Loka from "@/assets/images/loka.svg";
import Fil from "@/assets/images/fil.svg";
import Ocean from "@/assets/images/ocean.svg";
import Comp from "@/assets/images/comp.svg";
import Tomo from "@/assets/images/tomo.svg";
import Key from "@/assets/images/key.svg";
import Vite from "@/assets/images/vite.svg";
import Bat from "@/assets/images/bat.svg";
import Gala from "@/assets/images/gala.svg";
import Rad from "@/assets/images/rad.svg";
import Ankr from "@/assets/images/ankr.svg";
import Cfx from "@/assets/images/cfx.svg";
import Celo from "@/assets/images/celo.svg";
import Iotx from "@/assets/images/iotx.svg";
import Crv from "@/assets/images/crv.svg";
import Mith from "@/assets/images/mith.svg";
import Celr from "@/assets/images/celr.svg";
import Oxt from "@/assets/images/oxt.svg";
import Fio from "@/assets/images/fio.svg";
import Scrt from "@/assets/images/scrt.svg";
import Audio from "@/assets/images/audio.svg";
import Flm from "@/assets/images/flm.svg";
import Mdx from "@/assets/images/mdx.svg";
import Qtum from "@/assets/images/qtum.svg";
import Bnt from "@/assets/images/bnt.svg";
import Xvs from "@/assets/images/xvs.svg";
import Bico from "@/assets/images/bico.svg";
import Uma from "@/assets/images/uma.svg";
import Akro from "@/assets/images/akro.svg";
import Lsk from "@/assets/images/lsk.svg";
import Dock from "@/assets/images/dock.svg";
import Rep from "@/assets/images/rep.svg";
import Beam from "@/assets/images/beam.svg";
import Voxel from "@/assets/images/voxel.svg";
import Mana from "@/assets/images/mana.svg";
import Rare from "@/assets/images/rare.svg";
import Adx from "@/assets/images/adx.svg";
import Ont from "@/assets/images/ont.svg";
import Sand from "@/assets/images/sand.svg";
import Cocos from "@/assets/images/cocos.svg";
import Alice from "@/assets/images/alice.svg";
import Mtl from "@/assets/images/mtl.svg";
import Wing from "@/assets/images/wing.svg";
import Bake from "@/assets/images/bake.svg";
import Strax from "@/assets/images/strax.svg";
import Perp from "@/assets/images/perp.svg";
import Epx from "@/assets/images/epx.svg";
import Yfi from "@/assets/images/yfi.svg";
import Nmr from "@/assets/images/nmr.svg";
import Pyr from "@/assets/images/pyr.svg";
import Bond from "@/assets/images/bond.svg";
import Jst from "@/assets/images/jst.svg";
import Powr from "@/assets/images/powr.svg";
import Fida from "@/assets/images/fida.svg";
import Paxg from "@/assets/images/paxg.svg";
import Chz from "@/assets/images/chz.svg";
import Arb from "@/assets/images/arb.svg";
import Not from "@/assets/images/not.svg";
import Card from "@/assets/images/atm_card.svg";

const initialState = {
  coins: [
    // {
    //   Coin: "Bank Card",
    //   Abbr: "USD",
    //   Image: Card,
    //   Alt: "usd",
    //   Total: 0,
    // },
    {
      Coin: "Bitcoin",
      Abbr: "BTC",
      Image: Btc,
      Alt: "btc",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Deposit: "Deposit",
      Withdraw: "Withdraw",
    },
    {
      Coin: "Ethereum",
      Abbr: "ETH",
      Image: Eth,
      Alt: "eth",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Deposit: "Deposit",
      Withdraw: "Withdraw",
    },
    {
      Coin: "Litecoin",
      Abbr: "LTC",
      Image: Ltc,
      Alt: "ltc",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Deposit: "Deposit",
      Withdraw: "Withdraw",
    },
    {
      Coin: "Tether",
      Abbr: "USDT",
      Image: Usdt,
      Alt: "usdt",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Deposit: "Deposit",
      Withdraw: "Withdraw",
    },
    {
      Coin: "Tron",
      Abbr: "TRX",
      Image: Trx,
      Alt: "trx",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Deposit: "Deposit",
      Withdraw: "Withdraw",
    },
    {
      Coin: "USD Coin",
      Abbr: "USDC",
      Image: Usdc,
      Alt: "usdc",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Deposit: "Deposit",
      Withdraw: "Withdraw",
    },
    {
      Coin: "Binance-Coin",
      Abbr: "BNB",
      Image: Bnb,
      Alt: "bnb",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Deposit: "Deposit",
      Withdraw: "Withdraw",
    },
    {
      Coin: "Bitcoin Cash",
      Abbr: "BCH",
      Image: Bch,
      Alt: "bch",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Deposit: "Deposit",
      Withdraw: "Withdraw",
    },
    {
      Coin: "Dogecoin",
      Abbr: "DOGE",
      Image: Doge,
      Alt: "doge",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Deposit: "Deposit",
      Withdraw: "Withdraw",
    },
    {
      Coin: "Monero",
      Abbr: "XMR",
      Image: Xmr,
      Alt: "xmr",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Deposit: "Deposit",
      Withdraw: "Withdraw",
    },
    {
      Coin: "Stellar",
      Abbr: "XLM",
      Image: Xlm,
      Alt: "xlm",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Deposit: "Deposit",
      Withdraw: "Withdraw",
    },
    {
      Coin: "Tezos",
      Abbr: "XTZ",
      Image: Xtz,
      Alt: "xtz",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Deposit: "Deposit",
      Withdraw: "Withdraw",
    },
    {
      Coin: "EOS",
      Abbr: "EOS",
      Image: Eos,
      Alt: "eos",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Deposit: "Deposit",
      Withdraw: "Withdraw",
    },
    {
      Coin: "SHIBA INU",
      Abbr: "SHIB",
      Image: Shib,
      Alt: "shib",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Deposit: "Deposit",
      Withdraw: "Withdraw",
    },
    {
      Coin: "Chainlink",
      Abbr: "LINK",
      Image: LinkCoin,
      Alt: "link",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Deposit: "Deposit",
      Withdraw: "Withdraw",
    },
    {
      Coin: "Ethereum Classic",
      Abbr: "ETC",
      Image: Etc,
      Alt: "etc",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Deposit: "Deposit",
      Withdraw: "Withdraw",
    },
    {
      Coin: "Ripple",
      Abbr: "XRP",
      Image: Xrp,
      Alt: "xrp",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Deposit: "Deposit",
      Withdraw: "Withdraw",
    },
    {
      Coin: "Cardano",
      Abbr: "ADA",
      Image: Ada,
      Alt: "ada",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Deposit: "Deposit",
      Withdraw: "Withdraw",
    },
    {
      Coin: "Dash",
      Abbr: "DASH",
      Image: Dash,
      Alt: "dash",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Deposit: "Deposit",
      Withdraw: "Withdraw",
    },
    {
      Coin: "Zcash",
      Abbr: "ZEC",
      Image: Zec,
      Alt: "zec",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Deposit: "Deposit",
      Withdraw: "Withdraw",
    },
    {
      Coin: "SOL",
      Abbr: "SOL",
      Image: Sol,
      Alt: "sol",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Deposit: "Deposit",
      Withdraw: "Withdraw",
    },
    {
      Coin: "LUNA",
      Abbr: "LUNA",
      Image: Luna,
      Alt: "luna",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "APE",
      Abbr: "APE",
      Image: Ape,
      Alt: "ape",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "DOT",
      Abbr: "DOT",
      Image: Dot,
      Alt: "dot",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "MATIC",
      Abbr: "MATIC",
      Image: Matic,
      Alt: "matic",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "NEAR",
      Abbr: "NEAR",
      Image: Near,
      Alt: "near",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "TWT",
      Abbr: "TWT",
      Image: Twt,
      Alt: "twt",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "RVN",
      Abbr: "RVN",
      Image: Rvn,
      Alt: "rvn",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "WOO",
      Abbr: "WOO",
      Image: Woo,
      Alt: "woo",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "GAL",
      Abbr: "GAL",
      Image: Gal,
      Alt: "gal",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "GNO",
      Abbr: "GNO",
      Image: Gno,
      Alt: "gno",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "ASTR",
      Abbr: "ASTR",
      Image: Astr,
      Alt: "astr",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "NEXO",
      Abbr: "NEXO",
      Image: Nexo,
      Alt: "nexo",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "LOKA",
      Abbr: "LOKA",
      Image: Loka,
      Alt: "loka",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "FIL",
      Abbr: "FIL",
      Image: Fil,
      Alt: "fil",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "OCEAN",
      Abbr: "OCEAN",
      Image: Ocean,
      Alt: "ocean",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "COMP",
      Abbr: "COMP",
      Image: Comp,
      Alt: "comp",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "TOMO",
      Abbr: "TOMO",
      Image: Tomo,
      Alt: "tomo",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "KEY",
      Abbr: "KEY",
      Image: Key,
      Alt: "key",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "VITE",
      Abbr: "VITE",
      Image: Vite,
      Alt: "vite",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "BAT",
      Abbr: "BAT",
      Image: Bat,
      Alt: "bat",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "GALA",
      Abbr: "GALA",
      Image: Gala,
      Alt: "gala",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "RAD",
      Abbr: "RAD",
      Image: Rad,
      Alt: "rad",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "ANKR",
      Abbr: "ANKR",
      Image: Ankr,
      Alt: "ankr",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "CFX",
      Abbr: "CFX",
      Image: Cfx,
      Alt: "cfx",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "CELO",
      Abbr: "CELO",
      Image: Celo,
      Alt: "celo",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "IOTX",
      Abbr: "IOTX",
      Image: Iotx,
      Alt: "iotx",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "CRV",
      Abbr: "CRV",
      Image: Crv,
      Alt: "crv",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "MITH",
      Abbr: "MITH",
      Image: Mith,
      Alt: "mith",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "CELR",
      Abbr: "CELR",
      Image: Celr,
      Alt: "celr",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "OXT",
      Abbr: "OXT",
      Image: Oxt,
      Alt: "oxt",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "FIO",
      Abbr: "FIO",
      Image: Fio,
      Alt: "fio",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "SCRT",
      Abbr: "SCRT",
      Image: Scrt,
      Alt: "scrt",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "AUDIO",
      Abbr: "AUDIO",
      Image: Audio,
      Alt: "audio",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "FLM",
      Abbr: "FLM",
      Image: Flm,
      Alt: "flm",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "MDX",
      Abbr: "MDX",
      Image: Mdx,
      Alt: "mdx",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "QTUM",
      Abbr: "QTUM",
      Image: Qtum,
      Alt: "qtum",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "BNT",
      Abbr: "BNT",
      Image: Bnt,
      Alt: "bnt",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "XVS",
      Abbr: "XVS",
      Image: Xvs,
      Alt: "xvs",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "BICO",
      Abbr: "BICO",
      Image: Bico,
      Alt: "bico",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "UMA",
      Abbr: "UMA",
      Image: Uma,
      Alt: "uma",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "AKRO",
      Abbr: "AKRO",
      Image: Akro,
      Alt: "akro",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "LSK",
      Abbr: "LSK",
      Image: Lsk,
      Alt: "lsk",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "DOCK",
      Abbr: "DOCK",
      Image: Dock,
      Alt: "dock",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "REP",
      Abbr: "REP",
      Image: Rep,
      Alt: "rep",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "BEAM",
      Abbr: "BEAM",
      Image: Beam,
      Alt: "beam",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "VOXEL",
      Abbr: "VOXEL",
      Image: Voxel,
      Alt: "voxel",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "MANA",
      Abbr: "MANA",
      Image: Mana,
      Alt: "mana",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "RARE",
      Abbr: "RARE",
      Image: Rare,
      Alt: "rare",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "ADX",
      Abbr: "ADX",
      Image: Adx,
      Alt: "adx",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "ONT",
      Abbr: "ONT",
      Image: Ont,
      Alt: "ont",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "SAND",
      Abbr: "SAND",
      Image: Sand,
      Alt: "sand",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "COCOS",
      Abbr: "COCOS",
      Image: Cocos,
      Alt: "cocos",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "ALICE",
      Abbr: "ALICE",
      Image: Alice,
      Alt: "alice",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "MTL",
      Abbr: "MTL",
      Image: Mtl,
      Alt: "mtl",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "WING",
      Abbr: "WING",
      Image: Wing,
      Alt: "wing",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "BAKE",
      Abbr: "BAKE",
      Image: Bake,
      Alt: "bake",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "STRAX",
      Abbr: "STRAX",
      Image: Strax,
      Alt: "strax",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "PERP",
      Abbr: "PERP",
      Image: Perp,
      Alt: "perp",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "EPX",
      Abbr: "EPX",
      Image: Epx,
      Alt: "epx",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "YFI",
      Abbr: "YFI",
      Image: Yfi,
      Alt: "yfi",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "NMR",
      Abbr: "NMR",
      Image: Nmr,
      Alt: "nmr",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "PYR",
      Abbr: "PYR",
      Image: Pyr,
      Alt: "pyr",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "BOND",
      Abbr: "BOND",
      Image: Bond,
      Alt: "bond",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "JST",
      Abbr: "JST",
      Image: Jst,
      Alt: "jst",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "POWR",
      Abbr: "POWR",
      Image: Powr,
      Alt: "powr",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "FIDA",
      Abbr: "FIDA",
      Image: Fida,
      Alt: "fida",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "PAXG",
      Abbr: "PAXG",
      Image: Paxg,
      Alt: "paxg",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "CHZ",
      Abbr: "CHZ",
      Image: Chz,
      Alt: "chz",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "ARB",
      Abbr: "ARB",
      Image: Arb,
      Alt: "arb",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Withdraw: "Withdraw",
    },
    {
      Coin: "Notcoin",
      Abbr: "NOT",
      Image: Not,
      Alt: "not",
      Total: 0,
      InOrders: 0,
      Equivalent: 0,
      Deposit: "Deposit",
      Withdraw: "Withdraw",
    },
  ],
};

const rootReducer = (state = initialState) => {
  return state;
};

export default rootReducer;
