name: Deploy to cPanel

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust to your app's required Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build # Adjust to your build command if different

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.5.0
        with:
          server: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          local-dir: './build' # Adjust to your build directory if different
          server-dir: ${{ secrets.CPANEL_DIRECTORY }}
